
// import { Provider } from "react-redux";
import "./globals.css";
// import store from "@/store";


export const metadata = {
  title: "Clash e-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      {/* <Provider store={store}>
      </Provider> */}
      </body>
    </html>
  )
}
